version: "3"
services:
  run:
    image: ${DOCKER_REGISTRY}node:10
    working_dir: /workdir
    volumes:
      - ${HOME:-.}/.npmrc:/root/.npmrc:ro
      - ${HOME:-.}/.gitconfig:/root/.gitconfig:ro
      - ${HOME:-.}/.git-credentials:/root/.git-credentials:ro
      - ./package.json:/workdir/package.json
    entrypoint: bash -c "npm install"
